# Camel Servlet Configuration
camel.servlet.mapping.context-path=/api/*
camel.rest.binding-mode=json
server.port=8080

# Spring Data JPA & PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_manager?currentSchema=public
spring.datasource.username=user_manage_sis
spring.datasource.password=users1st
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ActiveMQ Configuration
# Forçar o uso de Spring Boot ActiveMQ properties que o CamelStarter entende
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# Se quiser usar o prefixo do Camel explicitamente
camel.component.activemq.broker-url=tcp://localhost:61616

activemq.topic=manage.user

# Swagger/OpenAPI
camel.rest.api-context-path=/api-doc
camel.rest.api-property.api.title=API de Gestao de Usuarios
camel.rest.api-property.api.version=1.0.0
springdoc.swagger-ui.path=/swagger-ui.html
